points:
  zones:
    matrix:
      columns:
        pinky:
          key:
            width: 1.5u
            bind: [0, 105, 0, 0]
            column_net: P008
            origin: [-u/2, -u/2]
        ring:
          key:
            width: u
            spread: 1.3u
            column_net: P002
        middle:
          key:
            width: u
            spread: 1.05u
            column_net: P115
        index:
          key:
            width: u
            spread: 1.05u
            column_net: P113
        inner:
          key:
            spread: 1.05u
            width: u
            column_net: P111
          rows: 
            bottombottom:
              skip: true
        innerinner:
          key:
            spread: 1.025u
            column_net: P010
          rows: 
            bottombottom:
              skip: true
      rows:
        bottombottom: 
          shift: [-4.9425U, 0]
          row_net: P024
        bottom: 
          row_net: P100
        home: 
          row_net: P104
        top: 
          row_net: P017
        num: 
          row_net: P029
        fn:
          row_net: P031
      anchor:
        shift: [200, -200]
    thumbs:
      key:
        width: 2U
        row_net: P024
        column_net: P010
      anchor:
        shift: [200, -200]

outlines:
  left: 
  - where: true
    bound: true
    what: rectangle
    size: [U + 4, U + 4]

pcbs: 
  left:
    outlines:
      main:
        outline: left
    footprints: 
      keyswitches:
        where: true
        what: mx 
        params: 
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: diode
        where: true
        params: 
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust: 
          shift: [1.8, -5.5]
      nice_nano:
        what: nice_nano
        params:
         orientation: up
        where:
          ref: matrix_pinky_home
        adjust:
          shift: [5, 19]
      jstph:
        what: jstph
        where:
          ref: matrix_pinky_fn
          shift: [-7, 5.5]
          rotate: -90
        params:
            side: B
            pos: pos
            neg: GND
      battery_switch:
        what: slider
        where:
            ref: matrix_pinky_bottom
            shift: [-9.5, -6.0]
            rotate: 90
        params:
            side: B
            from: pos
            to: RAW
      horizontal_reset:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: matrix_pinky_fn
          shift: [-9.5,-17.5]
          rotate: 90.0
           
